In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
obj = Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [11]:
obj2['d'] = 6

In [12]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
import numpy as np

In [16]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
'b' in obj2

True

In [18]:
'e' in obj2

False

In [19]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon':16000, 'Utah': 5000}

In [20]:
obj3 = pd.Series(sdata)

In [21]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [22]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [23]:
obj4 = pd.Series(sdata, index = states)

In [24]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [31]:
obj4.name = 'population'

In [32]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [33]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [34]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [35]:
obj.indezz = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [36]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [37]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
       'year': [2000, 2001, 2002, 2001, 2002, 2003], 
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [38]:
frame = pd.DataFrame(data)

In [39]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [40]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [41]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [42]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], 
                      index=['one', 'two', 'three', 'four', 'five', 'six'])

In [43]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [44]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [45]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [46]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [47]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [48]:
frame2['debt'] = np.arange(6.)

In [49]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [50]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [51]:
frame2['debt2'] = val

In [52]:
frame2

year   state  pop  debt  debt2
one    2000    Ohio  1.5   0.0    NaN
two    2001    Ohio  1.7   1.0   -1.2
three  2002    Ohio  3.6   2.0    NaN
four   2001  Nevada  2.4   3.0   -1.5
five   2002  Nevada  2.9   4.0   -1.7
six    2003  Nevada  3.2   5.0    NaN

In [53]:
frame2['eastern'] = frame2.state == 'Ohio'

In [54]:
frame2

year   state  pop  debt  debt2  eastern
one    2000    Ohio  1.5   0.0    NaN     True
two    2001    Ohio  1.7   1.0   -1.2     True
three  2002    Ohio  3.6   2.0    NaN     True
four   2001  Nevada  2.4   3.0   -1.5    False
five   2002  Nevada  2.9   4.0   -1.7    False
six    2003  Nevada  3.2   5.0    NaN    False

In [55]:
del frame2['eastern']

In [56]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'debt2'], dtype='object')

In [57]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 
       'Ohio': {2000: 1.5, 2001: 1.7, 2002:3.6}}

In [58]:
frame3 = pd.DataFrame(pop)

In [59]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [60]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [61]:
pdata = {'Ohio': frame3['Ohio'], 
         'Nevada': frame3['Nevada'][:2]}

In [62]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [63]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [64]:
frame4 = pd.DataFrame(pop, index=[2000, 2001, 2002])

In [65]:
frame4

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [66]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [67]:
frame2.values

array([[2000, 'Ohio', 1.5, 0.0, nan],
       [2001, 'Ohio', 1.7, 1.0, -1.2],
       [2002, 'Ohio', 3.6, 2.0, nan],
       [2001, 'Nevada', 2.4, 3.0, -1.5],
       [2002, 'Nevada', 2.9, 4.0, -1.7],
       [2003, 'Nevada', 3.2, 5.0, nan]], dtype=object)

In [68]:
obj = pd.Series(range(3), index = ['a', 'b', 'c'])

In [69]:
index = obj.index

In [70]:
index

Index(['a', 'b', 'c'], dtype='object')

In [71]:
obj

a    0
b    1
c    2
dtype: int64

In [72]:
index[1:]

Index(['b', 'c'], dtype='object')

In [73]:
labels = pd.Index(np.arange(3))

In [74]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [75]:
obj2 = obj2.astype(np.float64)

In [76]:
obj2

d    6.0
b    7.0
a   -5.0
c    3.0
dtype: float64

In [77]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [78]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [79]:
obj2.index is labels

True

In [80]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [81]:
frame3 = pd.DataFrame(pop ,index=[2000, 2001, 2002])

In [82]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [83]:
'Ohio' in frame3.columns

True

In [84]:
2003 in frame3.index

False

In [85]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [86]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [87]:
obj = pd.Series([4.5, 7.2, -5.2, 3.6], index=['d', 'b', 'a', 'c'])

In [88]:
obj

d    4.5
b    7.2
a   -5.2
c    3.6
dtype: float64

In [89]:
obj2 = obj.reindex(['a', 'b','c', 'd', 'e'])

In [90]:
obj2

a   -5.2
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [91]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [92]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [93]:
frame= pd.DataFrame(np.arange(9).reshape((3, 3)), 
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])

In [94]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [95]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [96]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [97]:
states = ['Texas', 'Utah', 'California']

In [98]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [99]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [100]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [101]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [102]:
new_obj = obj.drop('c')

In [103]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [104]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [105]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [106]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [107]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [108]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [109]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [110]:
obj.drop('c', inplace=True)

In [111]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [112]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [113]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [114]:
obj['b']

1.0

In [115]:
obj[1]

1.0

In [116]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [117]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [118]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [119]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [120]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [121]:
arr = np.array([True, False, True, False])

In [122]:
obj[arr]

a    0.0
c    2.0
dtype: float64

In [123]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [124]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [125]:
obj['b']

1.0

In [126]:
obj[1]

1.0

In [127]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [128]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [129]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [130]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [131]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [132]:
obj['b':'c'] = 5

In [133]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [134]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), 
                    index=['Ohio', 'Colorado', 'Utah', 'New York'], 
                    columns=['one', 'two', 'three', 'four'])

In [135]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [136]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [137]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [138]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [139]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [140]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [141]:
data[data < 5] = 0

In [142]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [143]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [144]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [145]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [146]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [147]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [148]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [149]:
ser = pd.Series(np.arange(3.))

In [150]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [151]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [152]:
ser2[-1]

2.0

In [153]:
ser[:1]

0    0.0
dtype: float64

In [154]:
ser[:-1]

0    0.0
1    1.0
dtype: float64

In [155]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [156]:
ser.iloc[:1]

0    0.0
dtype: float64

In [157]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [158]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], 
               index=['a', 'c', 'e', 'f', 'g'])

In [159]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [160]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [161]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [162]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), 
                   index=['Ohio', 'Texas', 'Colorado'])

In [163]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), 
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [164]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [165]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [166]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [167]:
df1 = pd.DataFrame({'A': [1, 2]})

In [168]:
df2 = pd.DataFrame({'B': [3, 4]})

In [169]:
df1

A
0  1
1  2

In [170]:
df2

B
0  3
1  4

In [171]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [172]:
df1= pd.DataFrame(np.arange(12.).reshape((3, 4)),
                           columns=list('abcd'))

In [173]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), 
                   columns=list('abcde'))

In [174]:
df2.loc[1, 'b'] = np.nan

In [175]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [176]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [177]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [178]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [179]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [180]:
df1 * 8

a     b     c     d
0   0.0   8.0  16.0  24.0
1  32.0  40.0  48.0  56.0
2  64.0  72.0  80.0  88.0

In [181]:
df1 ** 2

a     b      c      d
0   0.0   1.0    4.0    9.0
1  16.0  25.0   36.0   49.0
2  64.0  81.0  100.0  121.0

In [182]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [183]:
df1.reindex([5, 6, 7], method='ffill')

a    b     c     d
5  8.0  9.0  10.0  11.0
6  8.0  9.0  10.0  11.0
7  8.0  9.0  10.0  11.0

In [184]:
arr = np.arange(12.).reshape((3, 4))

In [185]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [186]:
arr[0]

array([0., 1., 2., 3.])

In [187]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [188]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [189]:
 series = frame.iloc[0]

In [190]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [191]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [192]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [193]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [194]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [195]:
series3 = frame['d']

In [196]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [197]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [198]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [199]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [200]:
frame

b         d         e
Utah   -1.041074 -1.575214  1.819916
Ohio   -0.367765  0.811213 -0.154587
Texas  -1.173737  0.304741  0.750628
Oregon  0.143620 -0.154484  0.045530

In [201]:
np.abs(frame)

b         d         e
Utah    1.041074  1.575214  1.819916
Ohio    0.367765  0.811213  0.154587
Texas   1.173737  0.304741  0.750628
Oregon  0.143620  0.154484  0.045530

In [202]:
f = lambda x: x.max() - x.min()

In [203]:
frame.apply(f)

b    1.317357
d    2.386427
e    1.974503
dtype: float64

In [204]:
frame.apply(f, axis='columns')

Utah      3.395130
Ohio      1.178978
Texas     1.924365
Oregon    0.298104
dtype: float64

In [205]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [206]:
frame.apply(f)

b         d         e
min -1.173737 -1.575214 -0.154587
max  0.143620  0.811213  1.819916

In [207]:
format = lambda x: '%.2f' % x

In [208]:
frame.applymap(format)

b      d      e
Utah    -1.04  -1.58   1.82
Ohio    -0.37   0.81  -0.15
Texas   -1.17   0.30   0.75
Oregon   0.14  -0.15   0.05

In [209]:
frame['e'].map(format)

Utah       1.82
Ohio      -0.15
Texas      0.75
Oregon     0.05
Name: e, dtype: object

In [210]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [211]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [212]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), 
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])

In [213]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [214]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [215]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [216]:
obj = pd.Series([4, 7, -3, 2])

In [217]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [218]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [219]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [220]:
frame.sort_values(by='b')

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [221]:
frame.sort_values(by=['a', 'b'])

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [222]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [223]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [224]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [225]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [226]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})

In [227]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [228]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [229]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [230]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [231]:
obj.index.is_unique

False

In [232]:
obj['a']

a    0
a    1
dtype: int64

In [233]:
obj['c']

4

In [234]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a','a', 'b', 'b'])

In [235]:
df

0         1         2
a  1.576404 -0.900442 -0.378519
a  0.321394 -0.316067 -1.176422
b -0.476595 -0.986743 -1.328656
b  1.104611 -0.801211 -2.170956

In [236]:
df.loc['b']

0         1         2
b -0.476595 -0.986743 -1.328656
b  1.104611 -0.801211 -2.170956

In [237]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])

In [238]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [239]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [240]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [241]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [242]:
df.idxmax()

one    b
two    d
dtype: object

In [243]:
df.idxmin()

one    d
two    b
dtype: object

In [244]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [245]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [246]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [247]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [248]:
import pandas_datareader.data as web

all_data = {ticker: web.DataReader(ticker, 'stooq')
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [263]:
all_data

{'AAPL':                Open     High      Low    Close     Volume
 Date                                                     
 2022-01-04  182.630  182.940  179.120  179.700   99310438
 2022-01-03  177.830  182.880  177.710  182.010  104701220
 2021-12-31  178.085  179.230  177.260  177.570   64062261
 2021-12-30  179.470  180.570  178.090  178.200   59773014
 2021-12-29  179.330  180.630  178.140  179.380   62348931
 ...             ...      ...      ...      ...        ...
 2017-01-12   27.976   28.076   27.818   28.066  113336014
 2017-01-11   27.940   28.220   27.909   28.180  112384968
 2017-01-10   27.948   28.096   27.840   28.030   90027935
 2017-01-09   27.755   28.108   27.752   28.000  134441591
 2017-01-06   27.483   27.808   27.411   27.746  131404883
 
 [1258 rows x 5 columns],
 'IBM':               Open     High     Low   Close   Volume
 Date                                                
 2022-01-04  136.10  139.950  135.90  138.02  7300011
 2022-01-03  134.07  136.295

In [250]:
open_price = pd.DataFrame({ticker: data['Open']
                          for ticker, data in all_data.items()})

In [251]:
open_price

AAPL     IBM     MSFT     GOOG
Date                                         
2022-01-04  182.630  136.10  334.830  2911.01
2022-01-03  177.830  134.07  335.350  2889.51
2021-12-31  178.085  134.00  338.510  2910.88
2021-12-30  179.470  133.75  341.910  2929.00
2021-12-29  179.330  132.40  341.300  2928.59
...             ...     ...      ...      ...
2017-01-12   27.976  133.39   58.740   807.14
2017-01-11   27.940  132.03   58.319   805.00
2017-01-10   27.948  133.55   58.431   807.86
2017-01-09   27.755  134.73   58.458   806.40
2017-01-06   27.483  134.13   58.031   795.26

[1258 rows x 4 columns]

In [252]:
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [253]:
returns = open_price.pct_change()

In [254]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2017-01-12 -0.001927 -0.001123  0.007046 -0.000421
2017-01-11 -0.001287 -0.010196 -0.007167 -0.002651
2017-01-10  0.000286  0.011513  0.001920  0.003553
2017-01-09 -0.006906  0.008836  0.000462 -0.001807
2017-01-06 -0.009800 -0.004453 -0.007304 -0.013814

In [255]:
returns.head()

AAPL       IBM      MSFT      GOOG
Date                                              
2022-01-04       NaN       NaN       NaN       NaN
2022-01-03 -0.026283 -0.014916  0.001553 -0.007386
2021-12-31  0.001434 -0.000522  0.009423  0.007396
2021-12-30  0.007777 -0.001866  0.010044  0.006225
2021-12-29 -0.000780 -0.010093 -0.001784 -0.000140

In [256]:
returns['MSFT'].corr(returns['IBM'])

0.4306444095331557

In [257]:
returns['MSFT'].cov(returns['IBM'])

0.00010353362854563221

In [258]:
returns.MSFT.corr(returns.IBM)

0.4306444095331557

In [259]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.370106  0.715005  0.643367
IBM   0.370106  1.000000  0.430644  0.410815
MSFT  0.715005  0.430644  1.000000  0.736193
GOOG  0.643367  0.410815  0.736193  1.000000

In [260]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000357  0.000107  0.000212  0.000203
IBM   0.000107  0.000234  0.000104  0.000105
MSFT  0.000212  0.000104  0.000247  0.000194
GOOG  0.000203  0.000105  0.000194  0.000280

In [261]:
 returns.corrwith(returns.IBM)

AAPL    0.370106
IBM     1.000000
MSFT    0.430644
GOOG    0.410815
dtype: float64

In [262]:
returns.corrwith(volume)

AAPL    0.084323
IBM     0.097269
MSFT    0.099062
GOOG    0.106074
dtype: float64

In [264]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [265]:
uniques = obj.unique()

In [266]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [267]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [268]:
pd.value_counts(obj.values, sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [269]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [271]:
mask = obj.isin(['b', 'c'])

In [272]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [273]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [274]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [275]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [276]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [277]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                    'Qu2': [2, 3, 1, 2, 3],
                    'Qu3': [1, 5, 2, 4, 4]})

In [278]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [279]:
result = data.apply(pd.value_counts).fillna(0)

In [280]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [281]:
returns.fillna(0)

AAPL       IBM      MSFT      GOOG
Date                                              
2022-01-04  0.000000  0.000000  0.000000  0.000000
2022-01-03 -0.026283 -0.014916  0.001553 -0.007386
2021-12-31  0.001434 -0.000522  0.009423  0.007396
2021-12-30  0.007777 -0.001866  0.010044  0.006225
2021-12-29 -0.000780 -0.010093 -0.001784 -0.000140
...              ...       ...       ...       ...
2017-01-12 -0.001927 -0.001123  0.007046 -0.000421
2017-01-11 -0.001287 -0.010196 -0.007167 -0.002651
2017-01-10  0.000286  0.011513  0.001920  0.003553
2017-01-09 -0.006906  0.008836  0.000462 -0.001807
2017-01-06 -0.009800 -0.004453 -0.007304 -0.013814

[1258 rows x 4 columns]

In [282]:
returns

AAPL       IBM      MSFT      GOOG
Date                                              
2022-01-04       NaN       NaN       NaN       NaN
2022-01-03 -0.026283 -0.014916  0.001553 -0.007386
2021-12-31  0.001434 -0.000522  0.009423  0.007396
2021-12-30  0.007777 -0.001866  0.010044  0.006225
2021-12-29 -0.000780 -0.010093 -0.001784 -0.000140
...              ...       ...       ...       ...
2017-01-12 -0.001927 -0.001123  0.007046 -0.000421
2017-01-11 -0.001287 -0.010196 -0.007167 -0.002651
2017-01-10  0.000286  0.011513  0.001920  0.003553
2017-01-09 -0.006906  0.008836  0.000462 -0.001807
2017-01-06 -0.009800 -0.004453 -0.007304 -0.013814

[1258 rows x 4 columns]